language: node_js
node_js:
  - 12

# Docker integration
services:
  - docker

# Pre-testing installs
install:
  - echo "without dependencies"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build . -t udagram-image-reverse-proxy
  - docker tag udagram-image-reverse-proxy fgaviria/udagram-image-reverse-proxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push fgaviria/udagram-image-reverse-proxy
